### ISSUE TITLE
表紙用画像データを収集する

### ISSUE THREAD

**Issue by huideyeren** [huidetang/XiandaiFenshuVol6#9]
```yaml
start_date: 2022/7/18
due_date: 2022/7/20
progress: 0
parent: 3
```

表紙の画像を調達する。
